#!/bin/bash

. gitvars.sh

git fetch
changes=$(get_change_count)

if [ "$changes" -le "1" ]; then
  echo "No squash needed. $changes commit(s) since origin/master."
  exit 0;
fi

git rebase -i HEAD~$(get_change_count)
